services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    command: >
      sh -c "
        bin/elasticsearch-plugin install analysis-nori --batch &&
        bin/elasticsearch
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=IfCLzAjxYJ2M2Ln4yMEg
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - elk

volumes:
  esdata:
    driver: local
  kibana-data:
    driver: local

networks:
  elk:
    driver: bridge