spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_URL}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  elasticsearch:
    username: elastic
    password: z0tX16xvXEI4R8R=cWj8
    uris: http://localhost:9202
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:static/sql/auction_schema.sql
        - classpath:static/sql/product_schema.sql